# Generated by Django 5.2.7 on 2025-11-06 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL),
        ),
    ]
