# Generated by Django 5.2.7 on 2025-11-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
