# Generated by Django 5.2.7 on 2025-11-07 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0005_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
