# Generated by Django 5.2.8 on 2025-11-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0007_group_user_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Graup',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='graup',
        ),
    ]
