# Generated by Django 5.2.8 on 2025-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0008_rename_group_graup_rename_group_user_graup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
