# Generated by Django 5.2.8 on 2025-11-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0009_user_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('scanner', 'Scanner'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('core', 'Core')], default='member', max_length=10),
        ),
    ]
