# Generated by Django 5.2.8 on 2025-11-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='penalty_count',
            new_name='penalty_level',
        ),
        migrations.AddField(
            model_name='penalty',
            name='previouslevel',
            field=models.IntegerField(default=0),
        ),
    ]
