# Generated by Django 5.2.8 on 2025-11-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0011_rename_penalty_count_user_penalty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='graup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='superdb.graup'),
        ),
    ]
