# Generated by Django 5.2.8 on 2025-11-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0012_event_graup'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='type',
            field=models.CharField(choices=[('reduce', 'Reduce'), ('add', 'Add'), ('pardon', 'Pardon'), ('ban', 'Ban')], default='add', max_length=10),
        ),
    ]
