# Generated by Django 5.2.8 on 2025-11-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0013_penalty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='penalties_processed',
            field=models.BooleanField(default=True),
        ),
    ]
