# Generated by Django 5.2.8 on 2025-11-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0014_event_penalties_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='penalties_processed',
            field=models.BooleanField(default=False),
        ),
    ]
