# Generated by Django 5.2.8 on 2025-11-22 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdb', '0015_alter_event_penalties_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_create', 'User Created'), ('user_edit', 'User Edited'), ('user_delete', 'User Deleted'), ('group_create', 'Group Created'), ('group_edit', 'Group Edited'), ('group_delete', 'Group Deleted'), ('event_create', 'Event Created'), ('event_edit', 'Event Edited'), ('event_delete', 'Event Deleted'), ('event_assign', 'Users Assigned to Event'), ('event_end', 'Event Ended'), ('checkin', 'User Checked In'), ('checkin_undo', 'Check-in Undone'), ('checkin_bulk', 'Bulk Check-in'), ('penalty_add', 'Penalty Added'), ('penalty_reduce', 'Penalty Reduced'), ('penalty_pardon', 'User Pardoned'), ('penalty_ban', 'User Banned'), ('penalty_auto', 'Auto Penalty (No-show)'), ('import_users', 'Users Imported'), ('scheduler_run', 'Scheduler Processed Events')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='superdb.event')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='superdb.graup')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
